name: "Pull Request Workflow"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: "bash"

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v3"
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/850812025847/locations/global/workloadIdentityPools/yashrajdighe-iac/providers/write-access"
          service_account: "yashrajdighe-iac@project-c0cea0c3-cf00-4dc8-b6d.iam.gserviceaccount.com"
